# 2.2 数据操作

In [1]:
import torch

torch.manual_seed(0)
torch.cuda.manual_seed(0)
print(torch.__version__)

1.3.0


## 2.2.1 创建`Tensor`

创建一个5x3的未初始化的`Tensor`：

In [29]:
x = torch.empty(5, 3)
print(x)

tensor([[-1.9393e+27,  3.0879e-41,  1.4013e-45],
        [ 1.4013e-45,  0.0000e+00,  0.0000e+00],
        [ 1.8077e-43,  0.0000e+00,  4.3038e+25],
        [ 3.0880e-41,  1.0241e+09,  4.5635e-41],
        [ 3.0268e-42,  0.0000e+00,  1.3452e-43]])


创建一个5x3的随机初始化的`Tensor`:



In [43]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9515, 0.6811, 0.0488],
        [0.8163, 0.4423, 0.2768],
        [0.8998, 0.0960, 0.5537],
        [0.3953, 0.8571, 0.6396],
        [0.7403, 0.6766, 0.3798]])


In [44]:
x.shape

torch.Size([5, 3])

创建一个5x3的long型全0的`Tensor`:



In [61]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接根据数据创建:

In [69]:
import math
x = torch.tensor([5.5, 3, math.pi, math.e])
print(x)

tensor([5.5000, 3.0000, 3.1416, 2.7183])


In [84]:
import numpy as np
x = torch.tensor(np.zeros((5, 7)), dtype=torch.long)
print(x)

tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]])


In [85]:
x = torch.tensor(np.eye(5))
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], dtype=torch.float64)


还可以通过现有的`Tensor`来创建，此方法会默认重用输入`Tensor`的一些属性，例如数据类型，除非自定义数据类型。

In [98]:
x = x.new_ones(5, 3, dtype=torch.float64)      # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 指定新的数据类型
print(x)                                    

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5560,  0.5477,  0.4383],
        [ 0.0394, -1.1895, -0.5015],
        [-0.1455,  0.1522, -1.4437],
        [-0.2284, -0.3552, -0.7219],
        [-0.3061,  1.3768,  1.0055]])


我们可以通过`shape`或者`size()`来获取`Tensor`的形状:

In [99]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [100]:
x = torch.arange(1, 10, 2)
print(x)

tensor([1, 3, 5, 7, 9])


In [102]:
x = torch.linspace(0, 9, 10)
print(x)
print(x.shape)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([10])


In [105]:
x = torch.rand(3, 4)
print(x)

tensor([[0.0901, 0.4229, 0.6737, 0.3176],
        [0.6898, 0.8330, 0.2389, 0.5049],
        [0.7067, 0.5392, 0.5418, 0.5624]])


In [107]:
x = torch.randn(3, 4)
print(x)

tensor([[ 1.0625, -0.4787, -0.6628, -0.4674],
        [-0.3516, -1.3869,  0.2270,  0.8023],
        [ 0.1408, -0.5820,  0.2239,  0.7616]])


In [111]:
help(torch.normal)

Help on built-in function normal:

normal(...)
    .. function:: normal(mean, std, out=None) -> Tensor
    
    Returns a tensor of random numbers drawn from separate normal distributions
    whose mean and standard deviation are given.
    
    The :attr:`mean` is a tensor with the mean of
    each output element's normal distribution
    
    The :attr:`std` is a tensor with the standard deviation of
    each output element's normal distribution
    
    The shapes of :attr:`mean` and :attr:`std` don't need to match, but the
    total number of elements in each tensor need to be the same.
    
    .. note:: When the shapes do not match, the shape of :attr:`mean`
              is used as the shape for the returned output tensor
    
    Args:
        mean (Tensor): the tensor of per-element means
        std (Tensor): the tensor of per-element standard deviations
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> torch.normal(mean=torch.arange(1., 1

In [115]:
x = torch.normal(0, 1, size=(5, 3))
print(x)

tensor([[ 0.0084,  0.9664,  0.7486],
        [ 1.2709,  0.2109,  1.5359],
        [-2.1960, -0.4223, -0.1316],
        [ 0.1957, -1.0772,  0.4173],
        [-0.1003,  1.2897,  0.9133]])


> 注意：返回的torch.Size其实就是一个tuple, 支持所有tuple的操作。

## 2.2.2 操作
### 算术操作
* **加法形式一**

In [116]:
x

tensor([[ 0.0084,  0.9664,  0.7486],
        [ 1.2709,  0.2109,  1.5359],
        [-2.1960, -0.4223, -0.1316],
        [ 0.1957, -1.0772,  0.4173],
        [-0.1003,  1.2897,  0.9133]])

In [126]:
y = torch.rand(5, 3)
print(y)

tensor([[0.8094, 0.7767, 0.5161],
        [0.3454, 0.3913, 0.5665],
        [0.7479, 0.1497, 0.9196],
        [0.4456, 0.0810, 0.2295],
        [0.9424, 0.9573, 0.0369]])


In [127]:
print(x + y)

tensor([[ 0.8178,  1.7431,  1.2647],
        [ 1.6163,  0.6021,  2.1023],
        [-1.4482, -0.2726,  0.7880],
        [ 0.6413, -0.9962,  0.6468],
        [ 0.8421,  2.2470,  0.9501]])


* **加法形式二**

In [128]:
print(torch.add(x, y))

tensor([[ 0.8178,  1.7431,  1.2647],
        [ 1.6163,  0.6021,  2.1023],
        [-1.4482, -0.2726,  0.7880],
        [ 0.6413, -0.9962,  0.6468],
        [ 0.8421,  2.2470,  0.9501]])


In [129]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8178,  1.7431,  1.2647],
        [ 1.6163,  0.6021,  2.1023],
        [-1.4482, -0.2726,  0.7880],
        [ 0.6413, -0.9962,  0.6468],
        [ 0.8421,  2.2470,  0.9501]])


* **加法形式三、inplace**

In [130]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.8178,  1.7431,  1.2647],
        [ 1.6163,  0.6021,  2.1023],
        [-1.4482, -0.2726,  0.7880],
        [ 0.6413, -0.9962,  0.6468],
        [ 0.8421,  2.2470,  0.9501]])


In [132]:
y

tensor([[ 0.8178,  1.7431,  1.2647],
        [ 1.6163,  0.6021,  2.1023],
        [-1.4482, -0.2726,  0.7880],
        [ 0.6413, -0.9962,  0.6468],
        [ 0.8421,  2.2470,  0.9501]])

In [137]:
y.t_()

tensor([[ 0.8178,  1.6163, -1.4482,  0.6413,  0.8421],
        [ 1.7431,  0.6021, -0.2726, -0.9962,  2.2470],
        [ 1.2647,  2.1023,  0.7880,  0.6468,  0.9501]])

In [138]:
x.copy_(y.t_())

tensor([[ 0.8178,  1.7431,  1.2647],
        [ 1.6163,  0.6021,  2.1023],
        [-1.4482, -0.2726,  0.7880],
        [ 0.6413, -0.9962,  0.6468],
        [ 0.8421,  2.2470,  0.9501]])

> **注：PyTorch操作inplace版本都有后缀"_", 例如`x.copy_(y), x.t_()`**

### 索引
我们还可以使用类似NumPy的索引操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。** 

In [140]:
x

tensor([[ 0.8178,  1.7431,  1.2647],
        [ 1.6163,  0.6021,  2.1023],
        [-1.4482, -0.2726,  0.7880],
        [ 0.6413, -0.9962,  0.6468],
        [ 0.8421,  2.2470,  0.9501]])

In [142]:
y = x[0, :]

In [143]:
y

tensor([0.8178, 1.7431, 1.2647])

In [144]:
y += 1

In [145]:
print(y)

tensor([1.8178, 2.7431, 2.2647])


In [146]:
print(x[0, :]) # 源tensor也被改了

tensor([1.8178, 2.7431, 2.2647])


### 改变形状
用`view()`来改变`Tensor`的形状：

In [147]:
x

tensor([[ 1.8178,  2.7431,  2.2647],
        [ 1.6163,  0.6021,  2.1023],
        [-1.4482, -0.2726,  0.7880],
        [ 0.6413, -0.9962,  0.6468],
        [ 0.8421,  2.2470,  0.9501]])

In [155]:
y = x.view(3, -1)

In [157]:
y.shape

torch.Size([3, 5])

In [159]:
x

tensor([[ 1.8178,  2.7431,  2.2647],
        [ 1.6163,  0.6021,  2.1023],
        [-1.4482, -0.2726,  0.7880],
        [ 0.6413, -0.9962,  0.6468],
        [ 0.8421,  2.2470,  0.9501]])

In [160]:
y

tensor([[ 1.8178,  2.7431,  2.2647,  1.6163,  0.6021],
        [ 2.1023, -1.4482, -0.2726,  0.7880,  0.6413],
        [-0.9962,  0.6468,  0.8421,  2.2470,  0.9501]])

In [158]:
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([3, 5]) torch.Size([3, 5])


**注意`view()`返回的新tensor与源tensor共享内存，也即更改其中的一个，另外一个也会跟着改变。**

In [161]:
y += 1

In [162]:
y

tensor([[ 2.8178,  3.7431,  3.2647,  2.6163,  1.6021],
        [ 3.1023, -0.4482,  0.7274,  1.7880,  1.6413],
        [ 0.0038,  1.6468,  1.8421,  3.2470,  1.9501]])

In [163]:
x

tensor([[ 2.8178,  3.7431,  3.2647],
        [ 2.6163,  1.6021,  3.1023],
        [-0.4482,  0.7274,  1.7880],
        [ 1.6413,  0.0038,  1.6468],
        [ 1.8421,  3.2470,  1.9501]])

In [14]:
print(x)
print(y) # 也加了1

tensor([[2.6035, 2.8110, 1.9549],
        [1.8797, 2.0482, 0.9555],
        [0.2771, 3.8663, 0.4345],
        [1.1604, 0.9746, 2.0739],
        [3.2628, 0.0825, 0.7749]])
tensor([2.6035, 2.8110, 1.9549, 1.8797, 2.0482, 0.9555, 0.2771, 3.8663, 0.4345,
        1.1604, 0.9746, 2.0739, 3.2628, 0.0825, 0.7749])


如果不想共享内存，推荐先用`clone`创造一个副本然后再使用`view`。

In [164]:
x_cp = x.clone().view(15)
print(x_cp)

tensor([ 2.8178,  3.7431,  3.2647,  2.6163,  1.6021,  3.1023, -0.4482,  0.7274,
         1.7880,  1.6413,  0.0038,  1.6468,  1.8421,  3.2470,  1.9501])


In [165]:
x -= 1
print(x)

tensor([[ 1.8178,  2.7431,  2.2647],
        [ 1.6163,  0.6021,  2.1023],
        [-1.4482, -0.2726,  0.7880],
        [ 0.6413, -0.9962,  0.6468],
        [ 0.8421,  2.2470,  0.9501]])


In [166]:
print(x_cp)

tensor([ 2.8178,  3.7431,  3.2647,  2.6163,  1.6021,  3.1023, -0.4482,  0.7274,
         1.7880,  1.6413,  0.0038,  1.6468,  1.8421,  3.2470,  1.9501])


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [175]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.4141])
0.41414621472358704


In [180]:
x.item()

0.41414621472358704

## 2.2.3 广播机制

In [181]:
x = torch.arange(1, 3).view(1, 2)
print(x)

tensor([[1, 2]])


In [182]:
y = torch.arange(1, 4).view(3, 1)
print(y)

tensor([[1],
        [2],
        [3]])


In [183]:
print(x + y)

tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 2.2.4 运算的内存开销

In [191]:
x = torch.tensor([1, 2])
print(x)

tensor([1, 2])


In [192]:
y = torch.tensor([3, 4])
print(y)

tensor([3, 4])


In [193]:
id_before = id(y)
print(id_before)

139871254006032


In [196]:
y = y + x

In [197]:
print(id(y))

139871255914688


In [198]:
print(id(y) == id_before)

False


In [199]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [201]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before)

True


In [204]:
y = x.view(1, -1)

In [206]:
print(y)
print(id(x) == id(y))

tensor([[1, 2]])
False


## 2.2.5 `Tensor`和NumPy相互转换
**`numpy()`和`from_numpy()`这两个函数产生的`Tensor`和NumPy array实际是使用的相同的内存，改变其中一个时另一个也会改变！！！**
### `Tensor`转NumPy

In [207]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [208]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [209]:
a += 1
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [212]:
b += 1
print(a)
print(b)

tensor([5., 5., 5., 5., 5.])
[5. 5. 5. 5. 5.]


### NumPy数组转`Tensor`

In [213]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [215]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [216]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [219]:
b += 1
print(a)
print(b)

[5. 5. 5. 5. 5.]
tensor([5., 5., 5., 5., 5.], dtype=torch.float64)


直接用`torch.tensor()`将NumPy数组转换成`Tensor`，该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存。

In [220]:
# 用torch.tensor()转换时不会共享内存
c = torch.tensor(a)
print(c)

tensor([5., 5., 5., 5., 5.], dtype=torch.float64)


In [222]:
a += 1
print(a)
print(c)

[7. 7. 7. 7. 7.]
tensor([5., 5., 5., 5., 5.], dtype=torch.float64)


In [231]:
c += 1
print(a)
print(c)

[12. 12. 12. 12. 12.]
tensor([12., 12., 12., 12., 12.], dtype=torch.float64)


In [232]:
c = torch.from_numpy(a)
c += 1
print(a)
print(c)

[13. 13. 13. 13. 13.]
tensor([13., 13., 13., 13., 13.], dtype=torch.float64)


## 2.2.6 `Tensor` on GPU

In [259]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)


In [234]:
x

tensor([1, 2], device='cuda:0')

In [235]:
y

tensor([1, 1], device='cuda:0')

In [236]:
z

tensor([2, 3], device='cuda:0')

In [237]:
z.to("cpu")

tensor([2, 3])

In [241]:
help(torch.cuda.current_device)

Help on function current_device in module torch.cuda:

current_device()
    Returns the index of a currently selected device.



In [243]:
torch.cuda.current_device()

0

In [245]:
torch.cuda.is_available()

True

In [251]:
torch.device("cpu")

device(type='cpu')

In [253]:
torch.device("cuda")

device(type='cuda')